'\" t
.TH TRI2FE 1 "August 26, 2013" "Utrecht University"
.UC 4
.SH NAME
tri2fe -n TriangleNodeFile -e TriangleElmFile
.SH DESCRIPTION
Converts output from \fItriangle\fP to input for \fIGTECTON\fP. Nodal point coordinates are output to file "tecin.dat.nps" and element connectivity to file "tecin.dat.elm". 
These filenames cannot be changed.
.SH SEE ALSO
triangle(1), pln(1), pln(7), opn(1), opn(7), plnplt(1), opnplt(1)
.SH "BUGS OR POSSIBLE FLAWS"
Report bugs to Rob Govers (email: r.govers@uu.nl).
