.\"	"@(#)hostname.3	1.0	12/15/93";
.TH HOSTNAME 3F-BSD "December 15, 1993" "Penn State Univ"
.UC 4
.SH NAME
hostname \- return local system hostname
.SH SYNOPSIS
character*(*) function hostname()
.br
.SH DESCRIPTION
The gethostname subroutine retrieves the standard host name of
the local host
.SH "SEE ALSO"
gethostname(3C)
.SH AUTHOR
Rob Govers.
