.\"	"@(#)rm.3	1.0	12/15/93";
.TH RM 3F-BSD "December 15, 1993" "Penn State Univ"
.UC 4
.SH NAME
rm \- remove directory entry; delete file
.SH SYNOPSIS
subroutine rm (pathname)
.br
character*(*) pathname
.SH DESCRIPTION
rm() removes the directory entry named by the path name pointed to
by path.
.SH "SEE ALSO"
unlink(2)
.SH AUTHOR
Rob Govers.
