/* routine to create GMT readable file to draw the colouring of elements
 * after partitioning (done with metis for example)
 * input files are: tecton element file, tecton nodal point file, element partitioning file
 * update 21-09-2011:
 * input files are: tecton element file, tecton nodal point file and partition info file
 * all generated by the partition routine
 */
#define TRUE       1
#define FALSE      0

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

main (int argc, char **argv)
{
  extern char *optarg;
  extern int optind;

//  char elementfile[256], nodalpointfile[256];
  char *elementfile = NULL, *nodalpointfile = NULL;
  char *partitionfile = NULL; 
  char *elementpartfile = NULL, *nodepartfile = NULL;
  char *matfile = NULL, *connfile = NULL, *gridfile = NULL, *nodefile = NULL, *colourfile = NULL;
  char record[BUFSIZ],error[BUFSIZ];
  FILE *fnp, *fel, *fpa, *fpn;
  FILE *fmat, *fconn, *fgrid, *fnode, *fcolour;

  int tmppart, tmpnumnp, tmpnumel;
  int i,j,flag,NUMNP, NDOF, NATTRIB, BM, ID;
  int NUMEL, AT1, AT2, n1, n2, n3;

  double *X, *Y;
  int *ELTS, *PART, *PART2;
  int parts[100];
  int nparts = 0;
  int hit = FALSE;

  NUMEL = 0; 
  NUMNP = 0;
  for (i=0;i<100;i++) {
	  parts[i]=-1;
  }

  
  while ((flag = getopt(argc, argv, "e:n:p:")) != EOF)
    switch (flag) {
	case 'e':
	  elementfile = optarg; break;
    case 'n':
      nodalpointfile =  optarg; break;
    case 'p':
      partitionfile =  optarg; break;
    default:
      fprintf(stderr,"Usage: %s -n tecin.nps -e tecin.elm -p partition.info\n",argv[0]); 
      exit(1);
    }

  if ( elementfile == NULL || nodalpointfile == NULL || partitionfile == NULL){
      fprintf(stderr,"Usage: %s -n tecin.nps -e tecin.elm -p partition.info\n",argv[0]); 
      exit(1);
  }
  if ( (fel = fopen(elementfile,"r")) == NULL ) {
    sprintf(error,"%s: open error on \"%s\"",argv[0],elementfile);
    perror(error); exit(1);
  }
  if ( (fnp = fopen(nodalpointfile,"r")) == NULL ) {
    sprintf(error,"%s: open error on \"%s\"",argv[0],nodalpointfile);
    perror(error); exit(1);
  }
  if ( (fpa = fopen(partitionfile,"r")) == NULL ) {
    sprintf(error,"%s: open error on \"%s\"",argv[0],partitionfile);
    perror(error); exit(1);
  }


  fscanf(fpa, "%d", &tmppart);
  while (fscanf(fpa, "%d %d %d", &tmppart, &tmpnumnp, &tmpnumel) != EOF) {
	  NUMNP = NUMNP + tmpnumnp;
	  NUMEL = NUMEL + tmpnumel;
  }
  fprintf(stdout, "Number of nodal points %d \n", NUMNP);
  fprintf(stdout, "Number of elements %d \n", NUMEL);
  fclose(fpa);

/*
  if ( fscanf(fnp,"%d %d %d %d",&NUMNP,&NDOF,&NATTRIB,&BM) == EOF ) {
    sprintf(error,"%s: EOF \"%s\"",argv[0],nodalpointfile);
    perror(error); exit(1);
  }
  if ( fscanf(fel,"%d %d %d",&NUMEL,&AT1,&AT2) == EOF ) {
    sprintf(error,"%s: EOF \"%s\"",argv[0],elementfile);
    perror(error); exit(1);
  }
*/
  ELTS = (int*) malloc(sizeof(int)*(NUMEL*3));
  PART = (int*) malloc(sizeof(int)*(NUMEL));
  PART2= (int*) malloc(sizeof(int)*(NUMNP));
  X = (double*) malloc(sizeof(double)*NUMNP);
  Y = (double*) malloc(sizeof(double)*NUMNP);

  for (i=0;i<NUMEL;i++) {
	  fscanf(fel,"%d %d %d %d %d %d %*d", &PART[i], &ID, &AT1, &n1, &n2, &n3);
	  ELTS[3*i] = n1-1;  ELTS[3*i+1] = n2-1;  ELTS[3*i+2] = n3-1;
//      fprintf(stdout, "%d %d %d\n", n1,n2,n3);
  }

  char str[256];
  for (i=0;i<NUMNP;i++) {
	  fgets(str,256,fnp);
	  sscanf(str,"%d %d %lf %lf",&PART2[i], &ID,&X[i],&Y[i]);
//      fprintf(stdout, "%lf %lf\n", X[i], Y[i]);
  }

	  parts[0]=PART2[0];
	  nparts=1;
	  for (i=1;i<NUMNP;i++) {
		  hit = FALSE;
		  for (j=0;j<nparts;j++) {
			  hit = hit || PART2[i]==parts[j];
		  }
		  if (!hit) {
			  parts[nparts] = PART2[i];
			  nparts++;
		  }
	  }

  fprintf(stdout, "number of parts: %d\n", nparts);
  for (i=0;i<nparts;i++) {
	  fprintf(stdout, "part[%d]: %d\n", i, parts[i]);
  }
  fclose(fel);
  fclose(fnp);

  matfile = "mat.dat";
  connfile = "conn.dat"; 
  gridfile = "grid.dat"; 
  colourfile = "mat.cpt";
  nodefile = "nodes.dat";

  if ( (fmat = fopen(matfile,"w")) == NULL ) {
    sprintf(error,"%s: open error on \"%s\"",argv[0],matfile);
    perror(error); exit(1);
  }
  if ( (fconn = fopen(connfile,"w")) == NULL ) {
    sprintf(error,"%s: open error on \"%s\"",argv[0],connfile);
    perror(error); exit(1);
  }
  if ( (fgrid = fopen(gridfile,"w")) == NULL ) {
    sprintf(error,"%s: open error on \"%s\"",argv[0],gridfile);
    perror(error); exit(1);
  }

  if ( (fnode = fopen(nodefile,"w")) == NULL ) {
    sprintf(error,"%s: open error on \"%s\"",argv[0],nodefile);
    perror(error); exit(1);
  }

  if ( (fcolour = fopen(colourfile,"w")) == NULL ) {
    sprintf(error,"%s: open error on \"%s\"",argv[0],colourfile);
    perror(error); exit(1);
  }

	  for (i=0;i<NUMEL;i++) {
		  fprintf(fmat,"%20.14g %20.14g %5d\n", X[ELTS[3*i]], Y[ELTS[3*i]], PART[i]+1);
		  fprintf(fmat,"%20.14g %20.14g %5d\n", X[ELTS[3*i+1]], Y[ELTS[3*i+1]], PART[i]+1);
		  fprintf(fmat,"%20.14g %20.14g %5d\n", X[ELTS[3*i+2]], Y[ELTS[3*i+2]], PART[i]+1);
	  }
	  fclose(fmat);

  for (i=0;i<NUMEL;i++) {
	  fprintf(fconn, "%d %d %d\n", 3*i, 3*i+1, 3*i+2);
  }

  for (i=0;i<NUMEL;i++) {
	  fprintf(fgrid,"%s\n", ">");
	  fprintf(fgrid,"%20.14g %20.14g\n", X[ELTS[3*i]], Y[ELTS[3*i]]);
	  fprintf(fgrid,"%20.14g %20.14g\n", X[ELTS[3*i+1]], Y[ELTS[3*i+1]]);
	  fprintf(fgrid,"%20.14g %20.14g\n", X[ELTS[3*i+2]], Y[ELTS[3*i+2]]);
	  fprintf(fgrid,"%20.14g %20.14g\n", X[ELTS[3*i]], Y[ELTS[3*i]]);
  }

//	  for (i=0;i<NUMEL;i++) {
//		  fprintf(fnode,"%20.14g %20.14g %5d\n", X[ELTS[3*i]], Y[ELTS[3*i]], PART2[ELTS[3*i]]+1);
//		  fprintf(fnode,"%20.14g %20.14g %5d\n", X[ELTS[3*i+1]], Y[ELTS[3*i+1]], PART2[ELTS[3*i+1]]+1);
//		  fprintf(fnode,"%20.14g %20.14g %5d\n", X[ELTS[3*i+2]], Y[ELTS[3*i+2]], PART2[ELTS[3*i+2]]+1);
//	  }
	  for (i=0;i<NUMNP;i++) {
		  fprintf(fnode,"%20.14g %20.14g %5d\n", X[i], Y[i], PART2[i]+1);
//		  fprintf(fnode,"%20.14g %20.14g %5d\n", X[ELTS[3*i+1]], Y[ELTS[3*i+1]], PART2[ELTS[3*i+1]]+1);
//		  fprintf(fnode,"%20.14g %20.14g %5d\n", X[ELTS[3*i+2]], Y[ELTS[3*i+2]], PART2[ELTS[3*i+2]]+1);
	  }
 
  int frac =  round(255/nparts);
  for (i=0;i<nparts;i++) {
	  double x1 = i*1.0 + 0.5;
	  double x2 = i*1.0 + 1.5;
	  int r = (nparts - i) * frac;
	  int g = i * frac;
	  int b = i * frac;
	  fprintf(stdout,"%f %d %d %d %f %d\n",x1,r,g,b,x2, frac);
		  
	  fprintf(fcolour, "%f %d %d %d %f %d %d %d\n", x1,r,g,b,x2,r,g,b);
  } 
  fclose(fconn); fclose(fgrid); fclose(fcolour); fclose(fnode);
  exit(0);
}
